export default {
    SET_USER_DATA: 'SET_USER_DATA',
    
    AUTH_ACTION_SUCCESS: 'AUTH_ACTION_SUCCESS',
    AUTH_ACTION_ERROR: 'AUTH_ACTION_ERROR',
    AUTH_ACTION_REQUEST: 'AUTH_ACTION_REQUEST',
    AUTH_ACTION_LOGIN: 'AUTH_ACTION_LOGIN',
    AUTH_ACTION_CLEAR_ERROR: 'AUTH_ACTION_CLEAR_ERROR',
    AUTH_ACTION_REGISTER: 'AUTH_ACTION_REGISTER',

    EDIT_BAND_INFO: 'EDIT_BAND_INFO',
    EDIT_BAND_INFO_SUCCESS: 'EDIT_BAND_INFO_SUCCESS',
    EDIT_BAND_INFO_ERROR: 'EDIT_BAND_INFO_ERROR',

    DELETE_ALBUM: 'DELETE_ALBUM',
    DELETE_ALBUM_SUCCESS: 'DELETE_ALBUM_SUCCESS',
    DELETE_ALBUM_ERROR: 'DELETE_ALBUM_ERROR',

    POST_ALBUM_DATA: 'POST_ALBUM_DATA',
    POST_ALBUM_DATA_SUCCESS: 'POST_ALBUM_DATA_SUCCESS',
    POST_ALBUM_DATA_ERROR: 'POST_ALBUM_DATA_ERROR',

    GET_ALBUM_LIST: 'GET_ALBUM_LIST',
    GET_ALBUM_LIST_SUCCESS: 'GET_ALBUM_LIST_SUCCESS',
    GET_ALBUM_LIST_ERROR: 'GET_ALBUM_LIST_ERROR',

    GET_SEARCH_BAND: 'GAT_SEARCH_BAND',
    GET_SEARCH_BAND_SUCCESS: 'GAT_SEARCH_BAND_SUCCESS',
    GET_SEARCH_BAND_ERROR: 'GAT_SEARCH_BAND_ERROR',

    GET_BAND_LIST: 'GET_BAND_LIST',
    GET_BAND_LIST_SUCCESS: 'GET_BAND_LIST_SUCCESS',
    GET_BAND_LIST_ERROR: 'GET_BAND_LIST_ERROR',

    POST_BAND_DATA: 'POST_BAND_DATA',
    POST_BAND_DATA_SUCCESS: 'POST_BAND_DATA_SUCCESS',
    POST_BAND_DATA_ERROR: 'POST_BAND_DATA_ERROR'
}